### PR TITLE
To do list structure

### PR DESCRIPTION
**Pull request by mrkamin**
What does this PR do?
This PR is raised to submit for code review in the Microvers dashboard of Mohammad Rafi Amin.

Description of the task to be completed 👎

Add the HTML for the structure.
Add the CSS file for the styling.
Use the linter tool that analyzes my source code to flag programming errors, bugs, stylistic errors, and suspicious constructs.
use JS structures
💯
Use WebPack structure
Use modules for better organizing
Use Flexbox a layout tool in CSS that helps you easily position HTML elements on the page.

### CODE REVIEW

**Comment by mrkamin** [comment]
final commit submit for code review

**Review by sumairq — COMMENTED** [review]
### Hi @mrkamin , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a working configuration for linters.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

@sumairq,
thanks for your good and valuable feedback.
I will try to submit a correct PR for review again.

**Comment by mrkamin** [comment]
Submit for Code Reviw

**Review by Nemwel-Boniface — CHANGES_REQUESTED** [review]
## Hello @mrkamin  :wave: ,
I am Nemwel your reviewer for this PR :man_beard: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## :heavy_multiplication_x:  Invalid Code Review Request :heavy_multiplication_x: 

As requested by the previous reviewer, kindly add the linters for the project

image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

@Nemwel-Boniface,
thanks for your good and valuable feedback.
I will take in to account your comment for my project.

**Comment by mrkamin** [comment]
Submit for Code Reviwe

**Review by muneebulrehman — CHANGES_REQUESTED** [review]
Hi @mrkamin , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR

## Required Changes ♻️

- [x] Kindly update your Readme file as per [this template. ](https://github.com/microverseinc/readme-template). Currently, you don't have a custom readme file. Having a nice README file shows the professionalism and seriousness of a candidate to a potential employer. 😊

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@muneebulrehman,
thanks for your good and valuable feedback. 
I will consider your comment and Update my REDME.

**Comment by mrkamin** [comment]
Update README

**Review by AmaduKamara — APPROVED** [review]
# Status: Approve 🟢🟢🟢

Hi @mrkamin,
Good job on making the changes asked by the previous reviewer 👍 
Your project is complete!  

## Highlights: 
✅ You used Gitflow correctly 👍 
✅ Linter checks passed 👍 
✅ Todo list structure achieved as expected 👍 

There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@AmaduKamara,
thanks for your good and valuable feedback.
```

**Review by sja-thedude — APPROVED** [review]
## Project Approved 👍 

Hi @mrkamin, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights:
- All linters passing
- All requirements completed
- Professional readme

giphy

Cheers and Happy coding!👏👏👏

Note: As it was approved previously, that's the reason I am approving it, however remember to update readme with new one from next time. 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

@sja-thedude,
thanks for your good and valuable feedback.

**Pull request merged**
